module.exports = {
    userTypes: {
         Admin:'Admin',
         Firm:'Firm', 
         Personnel:'Personnel'
    },
    applicationStatus: [
        'Pending',
        'Rejected By Council',
        'Recommended for Interview',
        'Recommended for further vetting',
        'Recommended for Council',
        'Failed',
        'Expired',
        'Declined for additional details',
        'Declined by Vetting Officer',
        'Awaiting Transcript',
        'Awaiting Payment',
        'Awaiting Admin Action',
        'Approved',
        'Activated'
    ],
    membershipStatus: ["Activated", "Not Activated"],
    paymentStatus: [
        "pending",
        "success",
        "declined",
        "canceled"
    ],
    personnelCategory: [
        "Engineer",
        "Engineer Craftsman",
        "Engineer Technician",
        "Engineer Technologist",
    ],
    firmCategory: [
        "Engineering (Special) Services Provision",
        "Engineering Construction",
        "Engineering Fabrication/Repairs/Maintenance",
        "Engineering Maintenance/Production",
        "Engineering Vendoring",
    ],
    engineeringBase: ['Nigeria', 'Expatriate'],
    rcRegType: [
        "Corporate",
        "Limited Liability",
        "Partnership",
        "Sole Partnership",
    ],
    firmType: ['Engineering', 'Consulting'],
    firmSize: [
        "A (For Business Value N1m - N20m)",
        "B (For Business Value N21m - N100m)",
        "C (For Business Value N101m - N500m)",
        "D (For Business Value > N500m)",
    ],
    professionalBody: {
        "Engineer": [],
        "Engineer Craftsman": [],
        "Engineer Technician": [],
        "Engineer Technologist": [],
    },
    states: [
        "Abia State",
        "Adamawa State",
        "Akwa Ibom State",
        "Anambra State",
        "Bauchi State",
        "Bayelsa State",
        "Benue State",
        "Borno State",
        "Cross River State",
        "Delta State",
        "Ebonyi State",
        "Edo",
        "Ekiti State",
        "Enugu State",
        "Federal Capital Territory",
        "Gombe State",
        "Imo State",
        "Jigawa State",
        "Kaduna State",
        "Kano State",
        "Katsina State",
        "Kebbi State",
        "Kogi State",
        "Kwara State",
        "Lagos State",
        "Nasarawa State",
        "Niger State",
        "Ogun State",
        "Ondo State",
        "Osun State",
        "Oyo State",
        "Plateau State",
        "Rivers State",
        "Sokoto State",
        "Taraba State",
        "Yobe State",
        "Zamfara State",
        "Other(Not Nigerian)",
    ],
}